export const strings = {
  foundation: {
    title: "Phase 0 foundation",
    description: "Shared expenses start with a reliable foundation: React, Express, MySQL and a consistent theme.",
    toggleTheme: "Toggle theme",
    dark: "Dark mode",
    light: "Light mode",
    moneyLabel: "Currency formatting example",
    apiLabel: "Backend API status",
    checking: "Checking backend...",
    connected: "Connected",
    offline: "Backend is unavailable. Please try again.",
    next: "Next: reusable components and the design-system playground.",
    notFound: "Page not found",
    home: "Go back home",
  },
  app: {
    name: "SaathHisab",
    tagline: "Split expenses with flatmates and friends",
  },
  auth: {
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to manage your shared expenses",
    signupTitle: "Create your account",
    signupSubtitle: "Start tracking and splitting expenses with your group",
    email: "Email address",
    password: "Password",
    name: "Full name",
    loginButton: "Sign In",
    signupButton: "Create Account",
    noAccount: "Don't have an account? Sign up",
    hasAccount: "Already have an account? Sign in",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    confirm: "Confirm",
    reject: "Reject",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try again",
    empty: "Nothing to show here yet",
    back: "Back",
  },
  balance: {
    getsBack: "gets back",
    owes: "owes",
    settled: "settled up",
    youGetBack: "You get back",
    youOwe: "You owe",
    youAreSettled: "You are all settled up",
    suggestedPayments: "Suggested payments",
  },
};
