export const uiStrings = {
 confirm: "Confirm", cancel: "Cancel", close: "Close", retry: "Try again", amount: "Amount",
 showPassword: "Show password", hidePassword: "Hide password", actionFailed: "The action failed. Please try again.",
 loadMore: "Load more", success: "Success", error: "Something went wrong", info: "Information",
 empty: "Nothing here yet", loading: "Loading", selectAll: "Select all", clearAll: "Clear selection",
 member: "Member", owner: "Owner", payer: "Paid by", participants: "Participants", category: "Category",
 copy: "Copy", copied: "Copied", copyFailed: "Could not copy. Select and copy the text manually.",
 theme: "Toggle theme", light: "Light mode", dark: "Dark mode", profile: "Profile", logout: "Sign out", userMenu: "Account menu",
 group: "Group", upload: "Drop a receipt image here, or choose a file", uploadHint: "JPEG, PNG or WebP, up to 5 MB",
 uploadError: "Choose a JPEG, PNG or WebP image up to 5 MB.", imageError: "This image could not be read.", removeImage: "Remove image", preview: "Receipt preview",
 startDate: "Start date", endDate: "End date", dateError: "End date must be on or after start date.",
 month: "Month", search: "Search expenses", allCategories: "All categories", allMembers: "All members",
 viewAll: "View all", noChart: "No spending data yet", primaryNav: "Main navigation", skipContent: "Skip to content",
 overview: "Overview", expenses: "Expenses", add: "Add", settle: "Settle", activity: "Activity", invite: "Invite",
 authDescription: "A little clarity for everything you share.", checkingAccess: "Checking access", denied: "You do not have access to this group.",
 status: { PENDING: "Pending", CONFIRMED: "Confirmed", REJECTED: "Rejected", CANCELLED: "Cancelled" },
};
